"""
Módulo de prompts de sistema para el Agente Supervisor Principal y Subagentes Especializados.
"""

from .system_prompts import (
    SYSTEM_PROMPT_SUPERVISOR,
    SYSTEM_PROMPT_PROCESS_PDF,
    SYSTEM_PROMPT_SCHOOL_LESSON_PLANS,
    SYSTEM_PROMPT_SCHOOL_ASSESSMENT_INSTRUMENTS,
    SYSTEM_PROMPT_SCHOOL_MULTIMODAL_RESOURCES,
    SYSTEM_PROMPT_SPECIALIZED_QUERIES,
)

__all__ = [
    "SYSTEM_PROMPT_SUPERVISOR",
    "SYSTEM_PROMPT_PROCESS_PDF",
    "SYSTEM_PROMPT_SCHOOL_LESSON_PLANS",
    "SYSTEM_PROMPT_SCHOOL_ASSESSMENT_INSTRUMENTS",
    "SYSTEM_PROMPT_SCHOOL_MULTIMODAL_RESOURCES",
    "SYSTEM_PROMPT_SPECIALIZED_QUERIES",
]
