"""
Core module for configuration, LLM model setup, collection names, input schemas, and prompt loader.
"""

from .config import (
    get_env_variable,
    DATABASE_URI,
    REDIS_URI,
    LANGGRAPH_AUTH,
    LANGSERVE_GRAPHS,
    LANGSMITH_TRACING,
    LANGSMITH_ENDPOINT,
    LANGSMITH_API_KEY,
    LANGSMITH_PROJECT,
    LANGGRAPH_CLOUD_LICENSE_KEY,
)
from .llm import llm
from .prompt_loader import load_prompt
from .collections import (
    AREAS,
    SUB_AREAS,
    VECTORS,
    LESSON_PLANS,
    ASSESSMENT_INSTRUMENTS,
    MULTIMODAL_RESOURCES,
    REFRESH_TOKENS,
    USERS,
)
from .tool_inputs import (
    Subarea,
    Contenido,
    IndicadorLogro,
    CompetenciaEspecifica,
    EncabezadoPlan,
    FilaCurricularPlan,
    InstrumentoGeneradoDetail,
    PlanificacionClase,
    CurricularAreaModel,
    SaveCurricularStructureInput,
    SaveLessonPlanInput,
    SaveAssessmentInstrumentInput,
    SaveMultimodalResourceInput,
    UpdateLessonPlanInput,
    UpdateAssessmentInstrumentInput,
    UpdateMultimodalResourceInput,
)

__all__ = [
    "get_env_variable",
    "DATABASE_URI",
    "REDIS_URI",
    "LANGGRAPH_AUTH",
    "LANGSERVE_GRAPHS",
    "LANGSMITH_TRACING",
    "LANGSMITH_ENDPOINT",
    "LANGSMITH_API_KEY",
    "LANGSMITH_PROJECT",
    "LANGGRAPH_CLOUD_LICENSE_KEY",
    "llm",
    "load_prompt",
    "AREAS",
    "SUB_AREAS",
    "VECTORS",
    "LESSON_PLANS",
    "ASSESSMENT_INSTRUMENTS",
    "MULTIMODAL_RESOURCES",
    "REFRESH_TOKENS",
    "USERS",
    "Subarea",
    "Contenido",
    "IndicadorLogro",
    "CompetenciaEspecifica",
    "EncabezadoPlan",
    "FilaCurricularPlan",
    "InstrumentoGeneradoDetail",
    "PlanificacionClase",
    "CurricularAreaModel",
    "SaveCurricularStructureInput",
    "SaveLessonPlanInput",
    "SaveAssessmentInstrumentInput",
    "SaveMultimodalResourceInput",
    "UpdateLessonPlanInput",
    "UpdateAssessmentInstrumentInput",
    "UpdateMultimodalResourceInput",
]
