AREAS = "cnb_areas"
SUBAREAS = "cnb_subareas"
VECTORES = "cnb_vectores"
PLANIFICACION = "planificaciones_generadas"
EVALUACION = "instrumentos_evaluacion"
RECURSOS = "recursos_multimodales"
REFRESH_TOKENS = "refresh_tokens"
USUARIOS = "usuarios"