"""
MongoDB collection name constants for the Planifica application.
"""
AREAS = "cnb_areas"
SUB_AREAS = "cnb_subareas"
VECTORS = "cnb_vectores"
LESSON_PLANS = "planificaciones_generadas"
ASSESSMENT_INSTRUMENTS = "instrumentos_evaluacion"
MULTIMODAL_RESOURCES = "recursos_multimodales"
REFRESH_TOKENS = "refresh_tokens"
USERS = "usuarios"